// fetch agent
export const FETCH_AGENT_START = 'FETCH_AGENT_START';
export const FETCH_AGENT_SUCCESS = 'FETCH_AGENT_SUCCESS';
export const FETCH_AGENT_FAIL = 'FETCH_AGENT_FAIL';
export const CLEAN_FETCH_AGENT_ERROR = 'CLEAN_FETCH_AGENT_ERROR';
