export const POST_DEPARTMENT_START = 'POST_DEPARTMENT_START';
export const POST_DEPARTMENT_SUCCESS = 'POST_DEPARTMENT_SUCCESS';
export const POST_DEPARTMENT_FAIL = 'POST_DEPARTMENT_FAIL';
export const CLEAN_POST_DEPARTMENT_ERROR = 'CLEAN_POST_DEPARTMENT_ERROR';