export const FETCH_DEPARTMENT_START = 'FETCH_DEPARTMENT_START';
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS';
export const FETCH_DEPARTMENT_FAIL = 'FETCH_DEPARTMENT_FAIL';
export const CLEAN_FETCH_DEPARTMENT_ERROR = 'CLEAN_FETCH_DEPARTMENT_ERROR';

// get department dropdown 
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_FAIL = 'GET_DEPARTMENT_FAIL';