export const POST_AGENT_START = 'POST_AGENT_START';
export const POST_AGENT_SUCCESS = 'POST_AGENT_SUCCESS';
export const POST_AGENT_FAIL = 'POST_AGENT_FAIL';
export const CLEAN_POST_AGENT_ERROR = 'CLEAN_POST_AGENT_ERROR';