export const GET_SUPPORT_GROUP_SUCCESS = 'GET_SUPPORT_GROUP_SUCCESS';
export const GET_SUPPORT_GROUP_FAIL = 'GET_SUPPORT_GROUP_FAIL';
export const POST_SUPPORT_GROUP_START = 'POST_SUPPORT_GROUP_START';
export const POST_SUPPORT_GROUP_SUCCESS = 'POST_SUPPORT_GROUP_SUCCESS';
export const POST_SUPPORT_GROUP_FAIL = 'POST_SUPPORT_GROUP_FAIL';
export const CLEAN_POST_SUPPORT_ERROR = 'CLEAN_POST_SUPPORT_ERROR';